version: "3"
services:
  prisoner-transactions-api:
    build:
      context: .
    network_mode: "host"
    container_name: prisoner-transactions-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  prisoner-transactions-api-cache:
    image: redis
    networks:
      - hmpps
    container_name: prisoner-transactions-api-cache
    restart: always
    ports:
      - '6378:6378'
    command: --port 6378


networks:
  hmpps:
