---
# Per environment values which override defaults in prisoner-transactions-api/values.yaml

generic-service:
  replicaCount: 1 # Using a single pod so I can use an in memory data store - can increase the pods again once the data store is externalised

  ingress:
    host: prisoner-transactions-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    APP_MAGICLINK_URL: https://prisoner-transactions-dev.hmpps.service.justice.gov.uk/link/verify-link?secret=

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
